// Code generated by gopkg.in/actgardner/gogen-avro.v5. DO NOT EDIT.
/*
 * SOURCE:
 *     gauge.avsc
 */

package avro

import (
	"io"
)

type Measure struct {
	Event_time int64
	Value      float32
}

func DeserializeMeasure(r io.Reader) (*Measure, error) {
	return readMeasure(r)
}

func NewMeasure() *Measure {
	v := &Measure{}

	return v
}

func (r *Measure) Schema() string {
	return "{\"doc:\":\"Gauge measurement information\",\"fields\":[{\"doc\":\"Unix epoch time in seconds for measurement event time\",\"name\":\"event_time\",\"type\":\"long\"},{\"doc\":\"Measurement value\",\"name\":\"value\",\"type\":\"float\"}],\"name\":\"measure\",\"namespace\":\"com.rainchasers.gauge\",\"type\":\"record\"}"
}

func (r *Measure) Serialize(w io.Writer) error {
	return writeMeasure(r, w)
}
