// Code generated by gopkg.in/actgardner/gogen-avro.v5. DO NOT EDIT.
/*
 * SOURCE:
 *     gauge.avsc
 */

package avro

type UnionMeasureSnapshot struct {
	Measure   *Measure
	Snapshot  *Snapshot
	UnionType UnionMeasureSnapshotTypeEnum
}

type UnionMeasureSnapshotTypeEnum int

const (
	UnionMeasureSnapshotTypeEnumMeasure  UnionMeasureSnapshotTypeEnum = 0
	UnionMeasureSnapshotTypeEnumSnapshot UnionMeasureSnapshotTypeEnum = 1
)
